Write a test to find sync IO
OctopusDeploy/Halibut pull request #439
Opened 2023-08-17 23:34 UTC by LukeButters

# Background

# Results

Fixes https://github.com/OctopusDeploy/Issues/issues/... _(optional public issue)_

Fixes https://github.com/OctopusDeploy/ResearchAndDevelopment/issues/... _(optional private issue)_

See [How we use GitHub Issues](https://github.com/OctopusDeploy/Issues/blob/master/docs/CONTRIBUTING.internal.md) (including [this flowchart](https://whimsical.com/r-d-incoming-work-workflow-aug-21-NsDnGQXcwBLwU66a88Zhue) 

## Before

![Before](https://user-images.githubusercontent.com/5088479/120727281-72762180-c51d-11eb-9776-85363dc084e2.png)

## After

![After](https://user-images.githubusercontent.com/5088479/120727258-67bb8c80-c51d-11eb-8d2a-e047095b2d01.png)

# How to review this PR

Quality :heavy_check_mark:

# Pre-requisites

- [ ] I have read [How we use GitHub Issues](https://github.com/OctopusDeploy/Issues/blob/master/docs/CONTRIBUTING.internal.md) for help deciding when and where it's appropriate to make an issue.
- [ ] I have considered informing or consulting the right people, according to the [ownership map](https://whimsical.com/ownership-map-NzbiD4HJyvhC9jNJNfS6TG).
- [ ] I have considered appropriate testing for my change.

2023-08-21 11:11 UTC, nathanwoctopusdeploy commented on source/Halibut.Tests/AsyncClientAndServiceMustNotUseSyncNetworkIO.cs
> +            // TODO: ASYNC ME UP!
?

2023-08-21 11:12 UTC, nathanwoctopusdeploy commented on source/Halibut.Tests/AsyncClientAndServiceMustNotUseSyncNetworkIO.cs
> +            // TODO: ASYNC ME UP!
testAsyncServicesAsWell -> testAsyncServices. Do we need the As Well?

2023-08-21 11:16 UTC, nathanwoctopusdeploy commented on source/Halibut.Tests/Support/Streams/NoSyncIOStream.cs
> +    public class NoSyncIoStream : DelegateStreamBase
Can this describe what it actually does? It doesn't do 'NoSyncIo', it just logs when sync IO occurs

2023-08-21 11:20 UTC, nathanwoctopusdeploy commented on source/Halibut/HalibutRuntimeBuilder.cs
> +        IBaseStreamWrapper baseStreamWrapper = new NoOpBaseStreamWrapper();
I'm not too fond of this. Can this not be null if it's not set and when null it does not change the call chains

2023-08-21 11:20 UTC, nathanwoctopusdeploy commented on source/Halibut/HalibutRuntimeBuilder.cs
> +        internal HalibutRuntimeBuilder WithBaseStreamWrapper(IBaseStreamWrapper baseStreamWrapper)
I don't know if BaseStreamWrapper really helps describe what it does. I think a good comment is needed here

2023-08-21 11:23 UTC, nathanwoctopusdeploy requested changes
I see the value in this test but I really don't like how invasive it is in Halibut to do this.

Are there other options? Even some nasty reflection to manipulate the Halibut Runtime / manipulate something that is exposed lower down in Halibut. Having to support this from the top down just for a test seems like a lot of noise for future readers to understand the reasoning behind.

2023-08-21 11:31 UTC, nathanwoctopusdeploy commented
> I see the value in this test but I really don't like how invasive it is in Halibut to do this.
> 
> Are there other options? Even some nasty reflection to manipulate the Halibut Runtime / manipulate something that is exposed lower down in Halibut. Having to support this from the top down just for a test seems like a lot of noise for future readers to understand the reasoning behind.

Could we do it with a conditional compilation directive? It's invasive and could change behaviour, so we would not want all tests to run like this, but a single test could be run with a specific compile time directive, separate nuke test -> build to compile with the directive etc. When the compilation directive is defined we wrap the base streams #if #endif for all related code and classes so it's guaranteed to be off by default. Constructor could add the IO logging stream to a static collection so the test can access it etc.

This would produce a lot less changes and also mean we only have those changes for one specific test.

2023-08-24 01:44 UTC, LukeButters commented on source/Halibut/Transport/WebSocketConnectionFactory.cs
> +        IStreamFactory streamFactory;
The test caught that we didn't use the factory in all places.

2023-08-24 01:44 UTC, LukeButters commented on source/Halibut/Transport/WebSocketConnectionFactory.cs
> +            var stream = streamFactory.CreateStream(client);
This is in `EstablishNewConnectionAsync` a new async method.

2023-08-24 23:28 UTC, nathanwoctopusdeploy commented on source/Halibut.Tests/AsyncClientAndServiceMustNotUseSyncNetworkIO.cs
> +                        .Where(s => !s.ToString().Contains("System.Threading.Tasks"))
Is this just filtering a noisy stack trace?

2023-08-24 23:30 UTC, nathanwoctopusdeploy approved these changes
Nice, LGTM

2023-08-24 23:45 UTC, merged